package mx.infotec.alimentoms.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AlimentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlimentoAllPropertiesEquals(Alimento expected, Alimento actual) {
        assertAlimentoAutoGeneratedPropertiesEquals(expected, actual);
        assertAlimentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlimentoAllUpdatablePropertiesEquals(Alimento expected, Alimento actual) {
        assertAlimentoUpdatableFieldsEquals(expected, actual);
        assertAlimentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlimentoAutoGeneratedPropertiesEquals(Alimento expected, Alimento actual) {
        assertThat(expected)
            .as("Verify Alimento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlimentoUpdatableFieldsEquals(Alimento expected, Alimento actual) {
        assertThat(expected)
            .as("Verify Alimento relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getPrecio()).as("check precio").isEqualTo(actual.getPrecio()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()))
            .satisfies(e -> assertThat(e.getFoto()).as("check foto").isEqualTo(actual.getFoto()))
            .satisfies(e -> assertThat(e.getFotoContentType()).as("check foto contenty type").isEqualTo(actual.getFotoContentType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAlimentoUpdatableRelationshipsEquals(Alimento expected, Alimento actual) {
        // empty method
    }
}
